name: Windows2019

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: If error, read the steps at README.md before run this action. Kalau error baca dulu langkahnya di README.md.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/rossum01/rdpw2/main/File/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/rossum01/rdpw2/main/File/a/master/a/b/wallpaper.png -OutFile wallpaper.bmp
        Invoke-WebRequest https://raw.githubusercontent.com/rossum01/rdpw2/main/File/wallpaper.bat -OutFile wallpaper.bat
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect to Ngrok Account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activate RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bmp D:\a\wallpaper.bmp
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Create Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region=ap 3389"'
    - name: Connect to your RDP - CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c start.bat
    - name: Success create! Obey GitHub rules! You can close tab now.
      run: | 
        Invoke-WebRequest https://github.com/rossum01/rdpw2/raw/main/File/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
